;;; package --- Summary

(prelude-require-package 'use-package)
(prelude-require-package 'init-loader)
(prelude-require-package 'smart-newline)
(prelude-require-package 'twittering-mode)
(prelude-require-package 'anything)
(prelude-require-package 'helm-descbinds)
(prelude-require-package 'viewer)
(prelude-require-package 'vline)
(prelude-require-package 'crosshairs)
(prelude-require-package 'smart-mode-line)
(prelude-require-package 'web-mode)
(prelude-require-package 'auto-complete)
(prelude-require-package 'ac-ispell)
(prelude-require-package 'guide-key)
(prelude-require-package 'comment-dwim-2)
(prelude-require-package 'dired-k)
(prelude-require-package 'helm-anything)
(prelude-require-package 'stripe-buffer)
(prelude-require-package 'google)
(prelude-require-package 'google-c-style)
(prelude-require-package 'google-this)
(prelude-require-package 'google-translate)
(prelude-require-package 'git-gutter)
(prelude-require-package 'yagist)
(prelude-require-package 'git-commit-training-wheels-mode)
(prelude-require-package 'ht)
(prelude-require-packages '(esup noflet))
(prelude-require-package 'auto-async-byte-compile)

(provide '00-require-packages)
;;; 00-require-packages.el ends here
